let p = document.createElement('p');
p.className = 'text';
p.innerHTML = 'это всего лишь текст';
document.body.append(p);
let div = document.createElement('div');
div.className = 'alert';
div.innerHTML = 'А это сообщение об ошибке';
document.body.append(div);
document.querySelector('.alert').style.backgroundColor = 'red';
document.querySelector('.alert').style.color = 'white';
document.querySelector('div').style.padding = '20px';